#constants.R
# Used to hold data needed amongst functions in various files

# Exaustive Data Frames
DF_ALL_DATA_ORIGINAL                    <- NULL
DF_ALL_UNIQUE_CITY_STATES               <- NULL
DF_UNIQUE_BEST_CITY_STATE               <- NULL
DF_UNIQUE_WORST_CITY_STATE              <- NULL
DF_ALL_CRIME_CHANGERS_CITY_STATE        <- NULL

DF_UNIQUE_ASC_POP_CITY_STATE            <- NULL
DF_UNIQUE_DESC_POP_CITY_STATE           <- NULL

LIST_UNIQUE_BEST_CLUSTERS               <- NULL
LIST_UNIQUE_WORST_CLUSTERS              <- NULL
LIST_EACH_ITEM_AS_DF_ALL_DATA           <- NULL
LIST_EACH_ITEM_AS_DF_CRIME_CHANGERS     <- NULL

# Will create
DF_UNIQUE_INCREASING_WORST_CITY_STATE   <- NULL
DF_UNIQUE_INCREASING_BETTER_CITY_STATE  <- NULL
DF_UNIQUE_DECREASING_WORSE_CITY_STATE   <- NULL
DF_UNIQUE_DECREASING_BETTER_CITY_STATE  <- NULL
DF_UNIQUE_STAGNANT_BETTER_CITY_STATE    <- NULL
DF_UNIQUE_STAGNANT_WORSE_CITY_STATE     <- NULL

# Lists






